"""Update cities.city_cn column with Chinese city names.

Uses a built-in mapping of well-known city Chinese names.
For unmapped cities, leaves city_cn NULL (can be filled later).

Usage:
  python3 update_city_cn.py
"""

from __future__ import annotations

import asyncio

import asyncpg

DB_HOST = "localhost"
DB_PORT = 5432
DB_USER = "postgres"
DB_PASSWORD = "22223333"
DB_NAME = "postgres"

# Comprehensive city English → Chinese mapping
CITY_CN = {
    # Africa
    "Luanda": "罗安达", "Ouagadougou": "瓦加杜古", "Cotonou": "科托努",
    "Cairo": "开罗", "Alexandria": "亚历山大", "Accra": "阿克拉", "Kumasi": "库马西",
    "Nairobi": "内罗毕", "Fes": "非斯", "Casablanca": "卡萨布兰卡",
    "Rabat": "拉巴特", "Marrakech": "马拉喀什", "Lagos": "拉各斯",
    "Abuja": "阿布贾", "Kano": "卡诺", "Ibadan": "伊巴丹", "Port Harcourt": "哈科特港",
    "Windhoek": "温得和克", "Victoria": "维多利亚", "Freetown": "弗里敦",
    "Tunis": "突尼斯", "Cape Town": "开普敦", "Johannesburg": "约翰内斯堡",
    "Lichtenburg": "利希滕堡", "Pretoria": "比勒陀利亚",
    "Banjul": "班珠尔", "Bissau": "比绍", "Conakry": "科纳克里",
    "Bamako": "巴马科", "Niamey": "尼亚美", "Nouakchott": "努瓦克肖特",
    "Dakar": "达喀尔", "Lome": "洛美", "Abidjan": "阿比让",
    "Kigali": "基加利", "Bujumbura": "布琼布拉", "Gaborone": "哈博罗内",
    "Maseru": "马塞卢", "Mbabane": "姆巴巴内", "Maputo": "马普托",
    "Harare": "哈拉雷", "Lusaka": "卢萨卡", "Dar es Salaam": "达累斯萨拉姆",
    "Kampala": "坎帕拉", "Addis Ababa": "亚的斯亚贝巴", "Asmara": "阿斯马拉",
    "Djibouti": "吉布提", "Mogadishu": "摩加迪沙", "Khartoum": "喀土穆",
    "Bangui": "班吉", "Malabo": "马拉博", "Sao Tome": "圣多美",
    "Libreville": "利伯维尔", "Brazzaville": "布拉柴维尔", "Kinshasa": "金沙萨",
    "Yaounde": "雅温得", "Ndjamena": "恩贾梅纳",
    # Middle East
    "Abu Dhabi": "阿布扎比", "Al Fujairah City": "富查伊拉城", "Dubai": "迪拜",
    "Fujairah": "富查伊拉", "Sharjah": "沙迦", "Kuwait City": "科威特城",
    "Beirut": "贝鲁特", "Muscat": "马斯喀特", "Salalah": "塞拉莱",
    "Riyadh": "利雅得", "Jeddah": "吉达", "Dammam": "达曼", "Mecca": "麦加",
    "Baghdad": "巴格达", "Erbil": "埃尔比勒",
    "Tehran": "德黑兰", "Isfahan": "伊斯法罕", "Shiraz": "设拉子",
    "Doha": "多哈",
    # Europe
    "Tirana": "地拉那", "Yerevan": "埃里温", "Baku": "巴库", "Sarajevo": "萨拉热窝",
    "Minsk": "明斯克",
    "Antwerp": "安特卫普", "Brussels": "布鲁塞尔", "Charleroi": "沙勒罗瓦",
    "Ghent": "根特", "Liege": "列日", "Mons": "蒙斯", "Namur": "那慕尔",
    "Zurich": "苏黎世", "Geneva": "日内瓦", "Bern": "伯尔尼", "Basel": "巴塞尔",
    "Lausanne": "洛桑", "Lugano": "卢加诺", "Winterthur": "温特图尔",
    "Nicosia": "尼科西亚",
    "Prague": "布拉格", "Brno": "布尔诺", "Ostrava": "俄斯特拉发", "Plzen": "比尔森",
    "Berlin": "柏林", "Bremen": "不来梅", "Cologne": "科隆", "Dortmund": "多特蒙德",
    "Dresden": "德累斯顿", "Dusseldorf": "杜塞尔多夫", "Essen": "埃森",
    "Frankfurt": "法兰克福", "Hamburg": "汉堡", "Hannover": "汉诺威",
    "Leipzig": "莱比锡", "Munich": "慕尼黑", "Nuremberg": "纽伦堡", "Stuttgart": "斯图加特",
    "Aarhus": "奥胡斯", "Copenhagen": "哥本哈根", "Odense": "欧登塞",
    "Tallinn": "塔林",
    "Barcelona": "巴塞罗那", "Bilbao": "毕尔巴鄂", "Madrid": "马德里",
    "Malaga": "马拉加", "Murcia": "穆尔西亚", "Seville": "塞维利亚",
    "Valencia": "瓦伦西亚", "Zaragoza": "萨拉戈萨",
    "Helsinki": "赫尔辛基", "Tampere": "坦佩雷", "Oulu": "奥卢",
    "Torshavn": "托尔斯港",
    "Bordeaux": "波尔多", "Grenoble": "格勒诺布尔", "Lille": "里尔",
    "Lyon": "里昂", "Marseille": "马赛", "Montpellier": "蒙彼利埃",
    "Nantes": "南特", "Nice": "尼斯", "Paris": "巴黎", "Rennes": "雷恩",
    "Strasbourg": "斯特拉斯堡", "Toulouse": "图卢兹",
    "London": "伦敦", "Manchester": "曼彻斯特", "Birmingham": "伯明翰",
    "Leeds": "利兹", "Bristol": "布里斯托", "Glasgow": "格拉斯哥",
    "Edinburgh": "爱丁堡", "Liverpool": "利物浦", "Nottingham": "诺丁汉",
    "Cardiff": "加的夫", "Belfast": "贝尔法斯特", "Leicester": "莱斯特",
    "Sheffield": "谢菲尔德", "Newcastle": "纽卡斯尔",
    "Tbilisi": "第比利斯",
    "Athens": "雅典", "Thessaloniki": "塞萨洛尼基",
    "Zagreb": "萨格勒布",
    "Budapest": "布达佩斯", "Debrecen": "德布勒森",
    "Dublin": "都柏林", "Cork": "科克",
    "Tel Aviv": "特拉维夫", "Jerusalem": "耶路撒冷", "Haifa": "海法",
    "Douglas": "道格拉斯",
    "Reykjavik": "雷克雅未克",
    "Rome": "罗马", "Milan": "米兰", "Naples": "那不勒斯", "Turin": "都灵",
    "Florence": "佛罗伦萨", "Bologna": "博洛尼亚", "Genoa": "热那亚",
    "Palermo": "巴勒莫", "Catania": "卡塔尼亚", "Venice": "威尼斯",
    "Verona": "维罗纳", "Bari": "巴里", "Padova": "帕多瓦",
    "Vilnius": "维尔纽斯", "Kaunas": "考纳斯",
    "Luxembourg": "卢森堡",
    "Riga": "里加",
    "Chisinau": "基希讷乌", "Skopje": "斯科普里",
    "Valletta": "瓦莱塔",
    "Oslo": "奥斯陆", "Bergen": "卑尔根", "Stavanger": "斯塔万格",
    "Trondheim": "特隆赫姆", "Tromso": "特罗姆瑟",
    "Amsterdam": "阿姆斯特丹", "Rotterdam": "鹿特丹", "The Hague": "海牙",
    "Utrecht": "乌特勒支", "Eindhoven": "埃因霍温", "Groningen": "格罗宁根",
    "Tilburg": "蒂尔堡", "Breda": "布雷达", "Nijmegen": "奈梅亨",
    "Arnhem": "阿纳姆", "Haarlem": "哈勒姆", "Leiden": "莱顿",
    "Maastricht": "马斯特里赫特", "Dordrecht": "多德雷赫特",
    "Zoetermeer": "祖特梅尔", "Enschede": "恩斯赫德", "Apeldoorn": "阿珀尔多伦",
    "Amersfoort": "阿默斯福特", "Zaanstad": "赞斯塔德", "Den Bosch": "斯海尔托亨博斯",
    "Deventer": "代芬特尔", "Almere": "阿尔梅勒", "Heerlen": "海尔伦",
    "Bergen op Zoom": "贝亨奥普佐姆", "Helmond": "海尔蒙德",
    "Veenendaal": "费嫩达尔", "Gouda": "豪达", "Venlo": "芬洛",
    "Vlaardingen": "弗拉尔丁根", "Alkmaar": "阿尔克马尔", "Hilversum": "希尔弗瑟姆",
    "Lelystad": "莱利斯塔德", "Hoorn": "霍伦", "Purmerend": "珀默伦德",
    "Sneek": "斯内克", "Emmen": "埃门", "Rijswijk": "赖斯韦克",
    "Wageningen": "瓦赫宁根", "Kampen": "坎彭", "Schiedam": "斯希丹",
    "Kerkrade": "克尔克拉德", "Weert": "韦尔特", "Roermond": "鲁尔蒙德",
    "Drachten": "德拉赫滕", "Capelle aan den IJssel": "卡佩勒河畔艾瑟尔",
    "Hengelo": "亨厄洛", "Nieuwkoop": "新库普", "Tiel": "蒂尔",
    "Culemborg": "屈伦博赫", "Wierden": "维尔登", "Harderwijk": "哈德韦克",
    "Ede": "埃德", "Barneveld": "巴内费尔德", "Doetinchem": "杜廷赫姆",
    "Zutphen": "聚特芬", "Stavoren": "斯塔沃伦", "Franeker": "弗拉内克",
    "Harlingen": "哈灵根", "Dokkum": "多克姆",
    "Warsaw": "华沙", "Krakow": "克拉科夫", "Wroclaw": "弗罗茨瓦夫",
    "Poznan": "波兹南", "Lodz": "罗兹", "Katowice": "卡托维兹",
    "Lublin": "卢布林", "Gdansk": "格但斯克",
    # Asia
    "Beijing": "北京", "Tianjin": "天津", "Changsha": "长沙", "Dezhou": "德州",
    "Guangzhou": "广州", "Guiyang": "贵阳", "Kunming": "昆明", "Nanjing": "南京",
    "Shanghai": "上海", "Shenzhen": "深圳", "Taishan": "台山", "Wuhan": "武汉",
    "Zhengzhou": "郑州", "Chengdu": "成都", "Chongqing": "重庆", "Dongguan": "东莞",
    "Foshan": "佛山", "Hangzhou": "杭州", "Hefei": "合肥", "Nanchang": "南昌",
    "Nanning": "南宁", "Ningbo": "宁波", "Qingdao": "青岛", "Suzhou": "苏州",
    "Xiamen": "厦门", "Zhongshan": "中山", "Zhuhai": "珠海", "Dalian": "大连",
    "Fuzhou": "福州", "Harbin": "哈尔滨", "Jinan": "济南", "Lhasa": "拉萨",
    "Shenyang": "沈阳", "Tangshan": "唐山", "Urumqi": "乌鲁木齐", "Wuxi": "无锡",
    "Xian": "西安", "Xining": "西宁",
    "Tokyo": "东京", "Osaka": "大阪", "Nagoya": "名古屋", "Sapporo": "札幌",
    "Fukuoka": "福冈", "Kobe": "神户", "Kyoto": "京都", "Hiroshima": "广岛",
    "Sendai": "仙台", "Nara": "奈良",
    "Seoul": "首尔", "Busan": "釜山", "Incheon": "仁川", "Daegu": "大邱",
    "Daejeon": "大田", "Gwangju": "光州",
    "Taipei": "台北", "Taichung": "台中", "Tainan": "台南", "Kaohsiung": "高雄",
    "Hsinchu": "新竹",
    "Hong Kong": "香港", "Macau": "澳门",
    "Mumbai": "孟买", "New Delhi": "新德里", "Chennai": "金奈", "Bangalore": "班加罗尔",
    "Hyderabad": "海得拉巴", "Kolkata": "加尔各答", "Pune": "浦那",
    "Ahmedabad": "艾哈迈达巴德", "Jaipur": "斋浦尔", "Lucknow": "勒克瑙",
    "Chandigarh": "昌迪加尔", "Indore": "印多尔", "Nagpur": "那格浦尔", "Kochi": "科钦",
    "Dhaka": "达卡",
    "Bangkok": "曼谷", "Chiang Mai": "清迈", "Pattaya": "芭提雅",
    "Phuket": "普吉", "Nakhon Ratchasima": "呵叻", "Khon Kaen": "孔敬",
    "Chiang Rai": "清莱", "Udon Thani": "乌隆他尼", "Hat Yai": "合艾",
    "Hua Hin": "华欣", "Korat": "呵叻", "Surat Thani": "素叻他尼",
    "Singapore": "新加坡",
    "Kuala Lumpur": "吉隆坡", "Johor Bahru": "新山", "Penang": "槟城", "Ipoh": "怡保",
    "Jakarta": "雅加达", "Surabaya": "泗水", "Bandung": "万隆",
    "Medan": "棉兰", "Semarang": "三宝垄", "Makassar": "望加锡",
    "Denpasar": "登巴萨", "Yogyakarta": "日惹", "Palembang": "巨港",
    "Manila": "马尼拉", "Cebu City": "宿务", "Davao": "达沃",
    "Quezon City": "奎松城", "Makati": "马卡蒂",
    "Hanoi": "河内", "Ho Chi Minh City": "胡志明市", "Da Nang": "岘港",
    "Can Tho": "芹苴", "Hai Phong": "海防",
    "Phnom Penh": "金边",
    "Vientiane": "万象",
    "Yangon": "仰光", "Mandalay": "曼德勒",
    "Karachi": "卡拉奇", "Lahore": "拉合尔", "Islamabad": "伊斯兰堡",
    "Faisalabad": "费萨拉巴德", "Peshawar": "白沙瓦",
    "Kathmandu": "加德满都",
    "Almaty": "阿拉木图", "Astana": "阿斯塔纳",
    "Bishkek": "比什凯克",
    "Dushanbe": "杜尚别",
    "Male": "马累",
    # Russia & CIS
    "Moscow": "莫斯科", "St Petersburg": "圣彼得堡", "Kazan": "喀山",
    "Novosibirsk": "新西伯利亚", "Yekaterinburg": "叶卡捷琳堡",
    "Nizhny Novgorod": "下诺夫哥罗德", "Samara": "萨马拉", "Sochi": "索契",
    "Krasnodar": "克拉斯诺达尔", "Rostov-on-Don": "顿河畔罗斯托夫",
    "Vladivostok": "海参崴", "Tomsk": "托木斯克", "Omsk": "鄂木斯克",
    "Khabarovsk": "哈巴罗夫斯克", "Tyumen": "秋明", "Chelyabinsk": "车里雅宾斯克",
    "Saratov": "萨拉托夫",
    # Turkey
    "Istanbul": "伊斯坦布尔", "Ankara": "安卡拉", "Izmir": "伊兹密尔",
    "Bursa": "布尔萨", "Antalya": "安塔利亚", "Adana": "阿达纳",
    # Americas
    "Toronto": "多伦多", "Montreal": "蒙特利尔", "Vancouver": "温哥华",
    "Ottawa": "渥太华", "Calgary": "卡尔加里", "Edmonton": "埃德蒙顿",
    "Winnipeg": "温尼伯", "Halifax": "哈利法克斯", "Quebec City": "魁北克城",
    "Saskatoon": "萨斯卡通", "Regina": "里贾纳", "St. Johns": "圣约翰斯",
    "Atlanta": "亚特兰大", "Boston": "波士顿", "Chicago": "芝加哥",
    "Dallas": "达拉斯", "Denver": "丹佛", "Houston": "休斯敦",
    "Los Angeles": "洛杉矶", "Miami": "迈阿密", "New York": "纽约",
    "Phoenix": "菲尼克斯", "San Francisco": "旧金山", "Seattle": "西雅图",
    "Washington": "华盛顿", "Minneapolis": "明尼阿波利斯", "San Diego": "圣地亚哥",
    "Portland": "波特兰", "Las Vegas": "拉斯维加斯", "Nashville": "纳什维尔",
    "Austin": "奥斯汀", "Columbus": "哥伦布", "Charlotte": "夏洛特",
    "Indianapolis": "印第安纳波利斯", "San Jose": "圣何塞", "Jacksonville": "杰克逊维尔",
    "Kansas City": "堪萨斯城", "Cleveland": "克利夫兰", "Baltimore": "巴尔的摩",
    "Milwaukee": "密尔沃基", "Albuquerque": "阿尔伯克基", "Omaha": "奥马哈",
    "Memphis": "孟菲斯", "Louisville": "路易维尔", "Richmond": "里士满",
    "Oklahoma City": "俄克拉荷马城", "Tucson": "图森", "New Orleans": "新奥尔良",
    "Pittsburgh": "匹兹堡", "Raleigh": "罗利", "Sacramento": "萨克拉门托",
    "Fort Worth": "沃斯堡", "El Paso": "埃尔帕索", "Detroit": "底特律",
    "Tampa": "坦帕", "St. Louis": "圣路易斯", "Orlando": "奥兰多",
    "Buffalo": "布法罗", "Cincinnati": "辛辛那提", "St. Petersburg": "圣彼得堡",
    "Norfolk": "诺福克", "Newark": "纽瓦克", "Plano": "普莱诺",
    "Lincoln": "林肯", "Boise": "博伊西", "Spokane": "斯波坎",
    "Chattanooga": "查塔努加", "Fresno": "弗雷斯诺", "Reno": "里诺",
    "Des Moines": "得梅因", "Honolulu": "檀香山", "Anchorage": "安克雷奇",
    "Bakersfield": "贝克斯菲尔德", "Wichita": "威奇托", "Madison": "麦迪逊",
    "Laredo": "拉雷多", "Garland": "加兰", "Lexington": "列克星敦",
    "Stockton": "斯托克顿", "Arlington": "阿灵顿", "Corpus Christi": "科珀斯克里斯蒂",
    "Irvine": "尔湾", "Rochester": "罗切斯特", "Glendale": "格伦代尔",
    "Henderson": "亨德森", "Jersey City": "泽西城", "Scottsdale": "斯科茨代尔",
    "St. Paul": "圣保罗", "North Las Vegas": "北拉斯维加斯", "Gilbert": "吉尔伯特",
    "Chesapeake": "切萨皮克", "Chandler": "钱德勒", "Fort Wayne": "韦恩堡",
    "Lubbock": "拉伯克", "Irving": "欧文", "Durham": "达勒姆",
    "Hialeah": "海厄利亚", "Fremont": "弗里蒙特", "Chula Vista": "丘拉维斯塔",
    "Philadelphia": "费城", "San Antonio": "圣安东尼奥",
    "Mexico City": "墨西哥城", "Guadalajara": "瓜达拉哈拉", "Monterrey": "蒙特雷",
    "Puebla": "普埃布拉", "Tijuana": "蒂华纳", "Merida": "梅里达",
    "Leon": "莱昂", "Cancun": "坎昆", "Chihuahua": "奇瓦瓦",
    "Aguascalientes": "阿瓜斯卡连特斯",
    "Buenos Aires": "布宜诺斯艾利斯", "Cordoba": "科尔多瓦", "Rosario": "罗萨里奥",
    "Mendoza": "门多萨", "La Plata": "拉普拉塔", "Mar del Plata": "马德普拉塔",
    "Tucuman": "图库曼", "Salta": "萨尔塔",
    "Sao Paulo": "圣保罗", "Rio de Janeiro": "里约热内卢", "Brasilia": "巴西利亚",
    "Salvador": "萨尔瓦多", "Fortaleza": "福塔莱萨", "Belo Horizonte": "贝洛奥里藏特",
    "Curitiba": "库里蒂巴", "Recife": "累西腓", "Porto Alegre": "阿雷格里港",
    "Manaus": "马瑙斯", "Belem": "贝伦", "Campinas": "坎皮纳斯",
    "Florianopolis": "弗洛里亚诺波利斯", "Natal": "纳塔尔", "Maceio": "马塞约",
    "Sao Luis": "圣路易斯", "Joao Pessoa": "若昂佩索阿", "Vitoria": "维多利亚",
    "Campo Grande": "大坎普", "Cuiaba": "库亚巴", "Aracaju": "阿拉卡茹",
    "Porto Velho": "韦柳港", "Macapa": "马卡帕", "Rio Branco": "里奥布兰科",
    "Boa Vista": "博阿维斯塔", "Palmas": "帕尔马斯", "Teresina": "特雷西纳",
    "Caracas": "加拉加斯", "Maracaibo": "马拉开波",
    "Santiago": "圣地亚哥", "Valparaiso": "瓦尔帕莱索", "Concepcion": "康塞普西翁",
    "Bogota": "波哥大", "Medellin": "麦德林", "Cali": "卡利",
    "Barranquilla": "巴兰基亚", "Cartagena": "卡塔赫纳",
    "Quito": "基多", "Guayaquil": "瓜亚基尔",
    "Lima": "利马",
    "La Paz": "拉巴斯", "Santa Cruz": "圣克鲁斯",
    "Asuncion": "亚松森",
    "Montevideo": "蒙得维的亚",
    "Georgetown": "乔治敦",
    "Paramaribo": "帕拉马里博",
    "Cayenne": "卡宴",
    "Havana": "哈瓦那",
    "Port-au-Prince": "太子港",
    "Kingston": "金斯敦",
    "Nassau": "拿骚",
    "Bridgetown": "布里奇敦",
    "Belize City": "伯利兹城", "Belmopan": "贝尔莫潘",
    "Hamilton": "汉密尔顿",
    "San Jose": "圣何塞", "Panama City": "巴拿马城",
    "Tegucigalpa": "特古西加尔巴", "San Salvador": "圣萨尔瓦多",
    "Guatemala City": "危地马拉城", "Managua": "马那瓜",
    "Port of Spain": "西班牙港",
    "Willemstad": "威廉斯塔德", "Oranjestad": "奥拉涅斯塔德",
    "Philipsburg": "菲利普斯堡",
    "St. George's": "圣乔治", "Castries": "卡斯特里",
    "Kingstown": "金斯敦", "Roseau": "罗索",
    "Basseterre": "巴斯特尔", "Gustavia": "古斯塔维亚",
    "Marigot": "马里戈特", "Santo Domingo": "圣多明戈",
    # Oceania & small islands
    "Noumea": "努美阿", "Port Louis": "路易港", "Port Vila": "维拉港",
    "Suva": "苏瓦", "Majuro": "马朱罗", "Palikir": "帕利基尔",
    "Yaren": "亚伦", "Funafuti": "富纳富提", "Nuku'alofa": "努库阿洛法",
    "Tarawa": "塔拉瓦", "Honiara": "霍尼亚拉", "Port Moresby": "莫尔兹比港",
    "Apia": "阿皮亚", "Adamstown": "亚当斯敦",
    "The Valley": "山谷",
    "St. John's": "圣约翰",
    # Misc
    "Dar es Salaam": "达累斯萨拉姆",
}


async def main() -> None:
    conn = await asyncpg.connect(
        host=DB_HOST, port=DB_PORT, user=DB_USER, password=DB_PASSWORD, database=DB_NAME,
    )

    rows = await conn.fetch("SELECT id, city FROM cities ORDER BY id")
    updated = 0
    for r in rows:
        cn = CITY_CN.get(r["city"])
        if cn:
            await conn.execute("UPDATE cities SET city_cn = $1 WHERE id = $2", cn, r["id"])
            updated += 1

    total = len(rows)
    null_count = await conn.fetchval("SELECT count(*) FROM cities WHERE city_cn IS NULL")
    print(f"Updated {updated}/{total} cities. {null_count} still NULL.")
    await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
